### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MualaniMarine** [UESTC-Ingress/IFSolver#19]
用mac设备和windows设备都复现了，报错完全一致，除了Total Keys的数量不一样。

Windows Python 3.8.4 opencv 3.4.11.43
Mac Python 3.9.1 opencv 2.4.13.7

Traceback (most recent call last):
  File "/Users/mac/IFSolver/main.py", line 117, in <module>
    main_manual()
  File "/Users/mac/IFSolver/main.py", line 107, in main_manual
    compared_portals = main_fast_cmp(splitted_img, portal_list, dlist, imgpos)
  File "/Users/mac/IFSolver/main.py", line 70, in main_fast_cmp
    pname, lat, lng, valid = cmpImage(
  File "/Users/mac/IFSolver/CmpUtils.py", line 28, in cmpImage
    print("Matches: " + str(pic_match[0]["matches"]))
IndexError: list index out of range

Traceback (most recent call last):
  File "main.py", line 117, in <module>
    main_manual()
  File "main.py", line 107, in main_manual
    compared_portals = main_fast_cmp(splitted_img, portal_list, dlist, imgpos)
  File "main.py", line 70, in main_fast_cmp
    pname, lat, lng, valid = cmpImage(
  File "C:\Users\Portal\Desktop\IFSolver\CmpUtils.py", line 28, in cmpImage
    print("Matches: " + str(pic_match[0]["matches"]))
IndexError: list index out of range

**Comment by YukariChiba** [comment]
The old version is now deprecated. Please try the latest version in `master` branch.
